#pragma once

#define SCREEN_HEIGHT 320
#define SCREEN_WIDTH 240

#define BUTTON_SIZE 54, 54
#define WEATHER_BUTTON_SIZE 188, 80
#define HOME_SQUARE_SIZE 16

#define HOME_BUTTON_POSITION 4, 270
#define WEATHER_APP_POSITION 27, 27
#define GALLERY_APP_POSITION 23, 131
#define MUSIC_APP_POSITION 94, 131
#define PAINT_APP_POSITION 165, 131
#define CHAT_APP_POSITION 23, 206
#define RGB_APP_POSITION 94, 206
#define INFO_APP_POSITION 165, 206

#define HOME_BUTTON HOME_BUTTON_POSITION, 64, 64
#define WEATHER_APP_BUTTON WEATHER_APP_POSITION, WEATHER_BUTTON_SIZE
#define GALLERY_APP_BUTTON GALLERY_APP_POSITION, BUTTON_SIZE
#define MUSIC_APP_BUTTON MUSIC_APP_POSITION, BUTTON_SIZE
#define PAINT_APP_BUTTON PAINT_APP_POSITION, BUTTON_SIZE
#define CHAT_APP_BUTTON CHAT_APP_POSITION, BUTTON_SIZE
#define RGB_APP_BUTTON RGB_APP_POSITION, BUTTON_SIZE
#define INFO_APP_BUTTON INFO_APP_POSITION, BUTTON_SIZE

#define TASKBAR_UPPER_LIMIT 276
#define BACKGROUND_RECT 0, 0, SCREEN_WIDTH, TASKBAR_UPPER_LIMIT
#define TASKBAR_RECT 0, TASKBAR_UPPER_LIMIT, SCREEN_WIDTH, SCREEN_HEIGHT
#define RIGHT_TASKBAR_SIDE_RECT 42, TASKBAR_UPPER_LIMIT, 198, 44 

#define RGB_COLOR_COUNT 16

#define MAX_WIFIS 10
#define MAX_WIFI_CONN_ATTEMPTS 10

#define NTP_SERVER "pool.ntp.org"
#define GALLERY_URL "https://cataas.com/cat?width=240&height=320"

#define ROTATION 2
#define ROTATION_2_CAL_PARAMS 4

#define LEFT 0
#define RIGHT 1
#define UP 2
#define DOWN 3
#define NEAR 4
#define FAR 5

/*
    ESP32 PINOUT

#define TFT_MISO 19
#define TFT_MOSI 23
#define TFT_SCLK 18
#define TFT_CS   15
#define TFT_DC    2
#define TFT_RST  -1 // Set TFT_RST to -1 if display RESET is connected to ESP32 board RST

#define TFT_BL   25 

#define TOUCH_CS 4 // 5?
*/

#define BUTTON_PIN 33
#define BUZZER_PIN 32
#define LED_PIN 27

#define SENSOR_SCL 22
#define SENSOR_SDA 21
#define APDS9960_INT 35
