#pragma once

#define SCREEN_HEIGHT 320
#define SCREEN_WIDTH 240

#define BUTTON_SIZE 54, 54
#define WEATHER_BUTTON_SIZE 188, 80
#define HOME_SQUARE_SIZE 16

#define HOME_BUTTON_POSITION 4, 270
#define WEATHER_APP_POSITION 27, 27
#define GALLERY_APP_POSITION 23, 131
#define MUSIC_APP_POSITION 94, 131
#define PAINT_APP_POSITION 165, 131
#define ALARM_APP_POSITION 23, 206
#define RGB_APP_POSITION 94, 206
#define INFO_APP_POSITION 165, 206

#define HOME_BUTTON HOME_BUTTON_POSITION, 64, 64
#define WEATHER_APP_BUTTON WEATHER_APP_POSITION, WEATHER_BUTTON_SIZE
#define GALLERY_APP_BUTTON GALLERY_APP_POSITION, BUTTON_SIZE
#define MUSIC_APP_BUTTON MUSIC_APP_POSITION, BUTTON_SIZE
#define PAINT_APP_BUTTON PAINT_APP_POSITION, BUTTON_SIZE
#define ALARM_APP_BUTTON ALARM_APP_POSITION, BUTTON_SIZE
#define RGB_APP_BUTTON RGB_APP_POSITION, BUTTON_SIZE
#define INFO_APP_BUTTON INFO_APP_POSITION, BUTTON_SIZE

#define TASKBAR_UPPER_LIMIT 276
#define BACKGROUND_RECT 0, 0, SCREEN_WIDTH, TASKBAR_UPPER_LIMIT
#define TASKBAR_RECT 0, TASKBAR_UPPER_LIMIT, SCREEN_WIDTH, SCREEN_HEIGHT

#define BUTTON_PIN 33
#define LED_PIN 27

#define SENSOR_SCL 22
#define SENSOR_SDA 21
#define APDS9960_INT 35

#define RGB_COLOR_COUNT 16

#define MAX_WIFIS 10
#define MAX_WIFI_CONN_ATTEMPTS 10